title: 更新中...
description: My Personal Stack Problems
author: C.Z.L.
github: https://github.com/pzyyll
about: 想中彩票想疯的菜鸡.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/pzyyll"
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/CChaloy"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"


share:
  twitter_username: CChaloy
  fb_appid: xxxx

urls:
    - text: About Me
      url: /about/
    #- text: My Projects
    #  url: /projects/

url: "https://pzyyll.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']